name: Automasi Preprocessing
on: [push]
jobs:
  preprocess-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Run Preprocessing
      run: python preprocessing/automate_tria_sania_oktavia.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: preprocessed-data
        path: preprocessing/dataset_preprocessing/
